import { Config } from 'tailwindcss';
import tailwindColours from './src/ts/tailwindColours';
import { tailwindScreens } from './src/ts/tailwindBreakpoints';

const config: Config = {
    content: [
    './src/vue/**/*.vue',
    './src/vue/**/*.ts',
    './src/ts/**/*.ts',
    ],
    prefix: 'u-',
    theme: {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      borderColor: (theme: any) => ({
          ...theme('colors'),
          transparent: 'transparent',
      }),
      colors: {
          ...tailwindColours,
          'body': '#333',
      },
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      backgroundColor: (theme: any) => ({
          ...theme('colors'),
          transparent: 'transparent',
      }),
      fontFamily: {
          'body': ['Montserrat', 'sans-serif'],
      },
      fontSize: {
          '2xs': '0.6rem',
          'xs': '0.75rem',
          'sm': '0.875rem',
          'base': '1rem',
          'lg': '1.125rem',
          'xl': '1.25rem',
          '2xl': '1.5rem',
          '3xl': '1.875rem',
          '4xl': '2.25rem',
          '5xl': '3rem',
          '6xl': '3.75rem',
          '7xl': '4.5rem',
          '8xl': '6rem',
          '9xl': '8rem',
      },
      screens: {
          ...tailwindScreens,
      },
      extend: {
          lineHeight: {
              negative: '0.8',
              body: '1.5',
              heading: '1.25',
          },
          spacing: {
              default: '2rem',
              paragraph: '1rem',
              heading: '1rem',
              gutter: '1.25rem',
              'gutter-lg': '2rem',
              'gutter-xl': '4rem',
          },
          transitionDuration: {
              default: "200ms",
              medium: "250ms",
          },
          zIndex: {
              behind: '-1',
              background: '0',
              base: '1',
              content: '10',
          },
      },
  },
  corePlugins: [
      'animation',
      'preflight',
      'accessibility',
      'alignContent',
      'alignItems',
      'alignSelf',
      'backgroundColor',
      'borderColor',
      'borderRadius',
      'borderStyle',
      'borderWidth',
      'boxShadow',
      'boxSizing',
      'cursor',
      'display',
      'fill',
      'flex',
      'flexDirection',
      'flexGrow',
      'flexShrink',
      'flexWrap',
      'fontFamily',
      'fontSize',
      'fontStyle',
      'fontWeight',
      'height',
      'justifyContent',
      'justifyItems',
      'justifySelf',
      'letterSpacing',
      'lineHeight',
      'inset',
      'margin',
      'maxHeight',
      'maxWidth',
      'minHeight',
      'minWidth',
      'objectPosition',
      'opacity',
      'order',
      'overflow',
      'padding',
      'position',
      'stroke',
      'strokeWidth',
      'tableLayout',
      'textAlign',
      'textColor',
      'textDecoration',
      'textTransform',
      'translate',
      'transform',
      'userSelect',
      'verticalAlign',
      'visibility',
      'whitespace',
      'width',
      'zIndex',
      'pointerEvents',
      'transitionProperty',
      'transitionDuration',
      'transitionProperty'
  ],
};
export default config;
